version: "3.8"
services:
  database:
    # Use mariadb:10.7.3 for mac
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: operational
    # To open the client, run 'mysql -u root -p'

  backend:
    command: yarn start:dev
    build: ./backend
    depends_on:
      - database
    environment:
      ENV: development
      NODE_ENV: development
      SERVER_PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: operational
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-cloud-credentials.json
    volumes:
      - "./backend:/app"

  frontend:
    command: yarn start:dev
    build:
      context: ./frontend
      target: runtime
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      ENV: development
      NODE_ENV: development
    volumes:
      - "./frontend:/app"

  proxy:
    build:
      context: ./proxy
      target: development
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    environment:
      ENV: development

volumes:
  db_data: {}
