version: "3.8"
services:
  database:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: operational
    # To open the client, run 'mysql -u root -p'

  backend:
    image: 591937736746.dkr.ecr.us-east-1.amazonaws.com/nitwit-backend:a6f8850a1d4552d0e27abe0491c96bf930098350
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    environment:
      ENV: production
      NODE_ENV: production
      SERVER_PORT: 3000
      REDIRECT_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: operational

  proxy:
    image: 591937736746.dkr.ecr.us-east-1.amazonaws.com/nitwit-proxy:cce52a580d43a227e2fd47386e0ccf5c2f24e2a5
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
    environment:
      ENV: production

volumes:
  db_data: {}
