version: "3.8"
services:
  database:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: operational
    # To open the client, run 'mysql -u root -p'

  backend:
    image: 591937736746.dkr.ecr.us-east-1.amazonaws.com/nitwit-backend:504d49bc0192576071382f2eb6d6d5fe9de78ae1
    depends_on:
      - database
    restart: always
    environment:
      ENV: production
      NODE_ENV: production
      SERVER_PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: operational

  proxy:
    image: 591937736746.dkr.ecr.us-east-1.amazonaws.com/nitwit-proxy:cce52a580d43a227e2fd47386e0ccf5c2f24e2a5
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
    environment:
      ENV: production

  redirect:
    image: 591937736746.dkr.ecr.us-east-1.amazonaws.com/nitwit-redirect:c6a352833b2675c59015f1aca884e90677e52f2c
    ports:
      - "8080:80"
    environment:
      ENV: production

volumes:
  db_data: {}
