version: "3.8"
services:
  database:
    image: "${DB_IMAGE}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: operational
    # To open the client, run 'mysql -u root -p'

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      NODE_ENV: "${ENV}"
      SERVER_PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: operational
    volumes:
      - "./backend:/app"
      - "backend_node_modules:/app/node_modules"

  frontend:
    build: ./frontend
    stdin_open: true
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "${ENV}"
    volumes:
      - "./frontend:/app"
      - "frontend_node_modules:/app/node_modules"

  reverse-proxy:
    build: "./proxy"
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data: {}
  backend_node_modules: {}
  frontend_node_modules: {}

# ENV is either "production" or "development". Remember to set it when running docker-compose.
