version: "3.8"
services:
  database:
    image: tobi312/rpi-mariadb:10.6-alpine
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: operational
    # To open the client, run 'mysql -u root -p'

  backend:
    image: nitwit-backend:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    environment:
      ENV: production
      NODE_ENV: production
      SERVER_PORT: 3000
      REDIRECT_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: operational

  frontend:
    image: nitwit-frontend:latest
    depends_on:
      - backend
    restart: always
    environment:
      ENV: production
      NODE_ENV: production

  proxy:
    image: nitwit-proxy:latest
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENV: production

volumes:
  db_data: {}
